### ISSUE TITLE
travis

### ISSUE THREAD

**Issue by RaphaelRaphael** [GreenwoodLab/funtooNorm#9]
The travis checking have to be unactivated since the new version is very different from the previous one.

**Comment by turgeonmaxime** [comment]
Can you explain what you mean? Travis is essentially checking if the package can be build correctly, which is a pre-requisite for sending it to Bioconductor/CRAN. In other words, if Travis fails, Bioconductor will reject the package.

**Comment by RaphaelRaphael** [comment]
Oh sorry, so travis should be ok. I was thinking about a kind of comparison in the code...
